url = https://google.com
urldemoqa = https://demoqa.com/automation-practice-form
firstname = First name
lastname = Last name
email = email@gmail.com
phone = 123456789
state= Haryana
gender = Male
hobbie = Sports
birthday = 01/01/2000
username = student
incorrectusername = student1
password = Password123
incorrectpassword = password123
urllogin = https://practicetestautomation.com/practice-test-login/
urlloading = https://the-internet.herokuapp.com/dynamic_loading/1
errorUsername = Your username is invalid!
errorPassword = Your password is invalid!
urlbutton = https://demoqa.com/buttons
doublemessage = You have done a double click
rightmessage = You have done a right click
clickmessage = You have done a dynamic click
textAddress = Test address
successText = Thanks for submitting the form
UPLOAD_FILE = src\\test\\download\\sampleFile.jpeg
uploadDownloadUrl = https://demoqa.com/upload-download
UPLOAD_MULTIPLE1 = src\\test\\download\\sampleFile.jpeg
UPLOAD_MULTIPLE2 = src\\test\\download\\sampleFile (1).jpeg
DOWNLOAD_FILE = sampleFile.jpeg
FILE_SIZE = 4096
USERNAME = student
PASSWORD = Aa@123456
LOGIN_PAGE = https://demoqa.com/login
ALERT_PAGE1 = https://the-internet.herokuapp.com/javascript_alerts
ALERT_RESULT = You successfully clicked an alert
CONFIRM_OK = You clicked: Ok
CONFIRM_CANCEL = You clicked: Cancel
TEXT_INPUT = Automation Testing
PROMPT_OK = You entered: Automation Testing
PROMPT_CANCEL = You entered: null
ALERT_PAGE2= https://www.selenium.dev/selenium/web/alerts.html
BROWSER_WINDOWS = https://demoqa.com/browser-windows
BROWSER_FRAME = https://demoqa.com/frames
NESTED_FRAME = https://demoqa.com/nestedframes

