url = https://google.com
urldemoqa = https://demoqa.com/automation-practice-form
firstname = First name
lastname = Last name
email = email@gmail.com
phone = 123456789
username = student
invalidusername = student1
password = Password123
invalidpassword = password123
urllogin = https://practicetestautomation.com/practice-test-login/
urlloading = https://the-internet.herokuapp.com/dynamic_loading/1

